---
title: "RUGS application for 'ggtedious'"
author: "Evangeline Reynolds"
date: "9/12/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dear RUGS committee members,

The following is a proposal for $??? for a RUGS sponsored workshop: 'ggtedious'.  The objective is to work on package building skills including the tedious tasks of writing tests and user facing messages (warnings and error) specific to ggplot2 extension packages.  Workshop participants will gain experience with these skills, and *video* will be posted so that a wider audience can benefit.  The 'ggtedious' github repo that we build is also indented to will provide future point of reference for participants. 

To our knowledge, no such resource workshop resource (repo and workshop recording) exists with a ggplot2 extension focus.

Specifically, at the workshop we will create two ggplot2 extension functions, geom_post() and geom_lollipop().  Then we will package these, using modern tooling and applying best practices. 


# The nature of the project and its goals

New developers may not be motivated to test and write error messages because the rewards aren't as tangible as writing functionality. "Look my test didn't fail" feels magnitudes less exciting that "look at this awesome thing my function accomplishes in one line of code - OMG".  

But the promise of testing is peace of mind; the promise is contentment not excitement.  

> 'Testing your code can be painful and tedious, but it greatly increases the quality of your code.'  - testthat introduction (probably Hadley Wickham)

Even when framed this way, testing and messaging still might not sound like much fun.  So, to get going in this space, we propose the {ggtedious} workshop to tie our hands --- committing to diving into this space of best practices among good company!  

After participating in ggtedious, participants will be accompanied by memories made at the ggtedious workshop when writing tests for their future projects. Given that, we'll try to make it a 'buzzy' good time!

The workshop will have in-person and remote contingents.  $150 is requested for a professional Zoom account purchase, which will allow the meeting to be recorded and span uninturrupted.

The remaining $XXX honorarium funds will divided between 2 consultants.  The first will guide the package building itself (tentatively Andrew Heiss), with great experience communicating code and methods and bringing energy and warmth to virtual formats (https://www.youtube.com/@AndrewHeiss/videos).  The other will lend their expertise in the business of making the package safe for users beyond the package author (testing, messaging, etc.); (Andy Teucher? - who's will  excitement for best practices promises to be contagious)?.  https://fosstodon.org/@andyteucher/111088512065072782

{ggtedious} is meant to complement other educational materials on focuses *only* on building ggplot2 extension functionality (https://github.com/EvaMaeRey/easy-geom-recipes) --- and not packaging.

The workshop will use specialized tools from *readme2pkg* so that the workshop lessons learned can be captured in a single narrative README.rmd, but also live in a viable package.


# The beginning and end dates for the project

We are working on scheduling the project for late-October or early November.

# A description of who will benefit from the project

Attendees will benefit from the project.  To keep the workshop intimate, we'll limit attendees to ?? or fewer online participants.  In person locations (unlimited attendees) will be at the University of Denver, US Military Academy at West Point Department of Mathematics, and elsewhere (possibly Yale Data Science and the University of Georgia). 

Furthermore, ggtedious will live on in a github Repo and posted video as a reference for other new-to-ggplot2 extension folks for reference. 

# A list of detailed activities along with relevant timelines

Pre Workshop

1. Secure technical participation and financial support from RUGS 1.5 months before meeting
2. Schedule meeting, coordinating with in person hosts and technical experts, and in-person locations
3. Announce at gathering for in-person locations & Announce opportunity for virtual participation and launch application form to participate
5. Select virtual participants (if pool is too large)

Workshop

1. Work on functionality
2. Build out package file structure, files

Post Workshop: 

Zoom video processing and Posting. ~ 1 month after meeting


# Your measure of success for the project

The test coverage and usability of this toy package will be the measure of success.  Creating a reference for future package builders and the workshop participants is the key an objective. 

# A detailed financial plan and list of expenses

$XXX total

- 1X professional Zoom membership, $150
- 2X \$XXX honorariums, $XXX 
